version: '3'

services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - '8056:80'
    volumes:
      - ./:/var/www/app
      - ./docker/server/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mariadb
    networks:
      - internal
    working_dir: /var/www/app

  mariadb:
    container_name: histfaqt-mariadb
    image: mariadb
    restart: on-failure
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: histfaqt
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/log:/var/log/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.111.1/28